# Generated by Django 5.1.3 on 2026-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_member_password_sitesettings_contact_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="it_support_message",
            field=models.TextField(
                blank=True,
                default="For member portal passwords and technical support, contact IT via WhatsApp",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="payment_instructions",
            field=models.TextField(
                blank=True,
                help_text="Bank account details, Mobile Money instructions, etc.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="success_button_text",
            field=models.CharField(
                blank=True, default="Return to Home", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="success_button_url",
            field=models.CharField(
                blank=True,
                default="home",
                help_text="URL name (e.g., 'home', 'dashboard') or full URL",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="success_message",
            field=models.TextField(
                blank=True,
                default="Thank you for joining KUSS! Your membership application has been received. We will review your details and contact you soon.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="treasurer_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the current Treasurer",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="treasurer_phone",
            field=models.CharField(
                blank=True,
                help_text="Treasurer's phone/Mobile Money number for fees",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp number with country code, e.g., +256772123456",
                max_length=20,
                null=True,
            ),
        ),
    ]
