# Generated by Django 5.1.3 on 2026-07-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_transactioncategory_financialreport_notification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("authors", models.CharField(max_length=500)),
                ("link", models.URLField(help_text="Full URL to the paper")),
                ("journal", models.CharField(blank=True, max_length=300)),
                ("publication_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-publication_date"],
            },
        ),
    ]
